### ISSUE TITLE
Strange porcupine-esque spikes seen in data

### ISSUE THREAD

**Issue by Ian-Goodall-Halliwell** [jordandekraker/superficial-white-matter#15]
Hello,

I found these strange spikes in sfwm surfaces generated from the micapipe module.

![Porc](https://github.com/user-attachments/assets/df05eab8-f569-4f86-b245-765aa7e1237b)

**Comment by jordandekraker** [comment]
Thanks @Ian-Goodall-Halliwell. If I remember correctly, we were working on a fix Fri afternoon and I think it was still failing. Can you please push the change to a new branch and I'll try to get it working?

**Comment by Ian-Goodall-Halliwell** [comment]
The format of the repository is changed considerably in my local clone, but here is a link to it [here](https://github.com/jordandekraker/superficial-white-matter/tree/Blurring)
